import React from 'react';
import Head from 'next/head';
import Footer from '../components/common/Footer';
import Header from '../components/common/Header';
import styles from '../styles/Home.module.css';

import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>who1</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='d-flex flex-column min-vh-100'>
        <Header />
        <Component {...pageProps} />
      </div>
    </div>
  );
}

export default MyApp;
